config/routes.rb
MissFacebook::Application.routes.draw do
  resources :users
 
  root :to => "tops#index"
 
  match 'auth/:provider/callback' => 'sessions#login', :via => :get
  match '/logout' => 'sessions#logout', :as => :logout, :via => :post
  match '/choice' => 'choice#index', :via => :get, :as => :choice
  
  match '/apis/choice_woman' => 'apis#choice_woman', :via => :post
  match '/apis/create_user_impression' => 'apis#create_user_impression', :via => :post  
  match '/apis/change_women' => 'apis#change_women', :via => :get
  match '/apis/create_score' => 'apis#create_score', :via => :post

  match '/statistics' => 'statistics#index', :via => :get 

  

end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
 
  def index
    set_history
    change_template
  end

  def man
  end

  def woman
  end

  #looked 男性:見た、女性:見られた
  #selected 男性:選んだ、女性:選ばれた
  private
  def set_history
    @looked_user_id = @login_user.man? ? @login_user.user_impressions.pluck(:to_user_id).uniq : UserImpression.to_user_id_is(@login_user.id).pluck(:user_id)
    @selected_user_id = @login_user.man? ? @login_user.user_likes.pluck('to_user_id').uniq : UserLike.to_user_id_is(@login_user.id).pluck(:user_id)
    @selected_user_count = @selected_user_id.size
  end
 
  def change_template
    render action: @login_user.man? ? 'man' : 'woman' 
  end
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/statistics/index.html.slim
はずれ

app/views/statistics/man.html.slim
article.row.col-md-offset-1.col-md-10.mt20
  section.row
    .col-md-6
      h1.your-rank-title 
        span.glyphicon.glyphicon-user
        | &nbsp;あなたの目利き度
      p.your-rank
        strong
          = @login_user.user_score ? @login_user.user_score.score : "-" 
        span.your-rank-unit &nbsp;点
    .col-md-6
      table.table.mt100
        tr
          th 今まで見た女性の数
          td
            = @looked_user_id.size
        tr
          th 選んだ女性の数
          td
            = @selected_user_count 

  section.row.mb40
    .col-md-12
      = link_to 'もっと女性を見る', choice_path, class:'col-md-6 col-md-offset-3 btn btn-primary btn-lg'

  section.row.mb40
    .col-md-12
      .row
        .col-md-12
          h2
            span.glyphicon.glyphicon-heart
            | &nbsp;あなたの選んだ女性（#{@selected_user_count} 人）
      .row
        - User.where(id: @selected_user_id).each do |user|
          .col-md-2
            = image_tag user.photo, class:"user-list-image"
            .text-center.user-caption
              strong.user-caption-name 
                = user.nick_name
              br 
              | Japan
              br
              | Rank #{user.rank}
              br
              - if user.friend_allow?
                = link_to 'メッセージを送る', "https://www.facebook.com/profile.php?id=#{user.uid}", class:'btn btn-primary btn-sm'
              - else
                span.btn.btn-primary.btn-sm メッセージ不可

  section.row.mb40
    .col-md-12
      = link_to 'もっと女性を見る', choice_path, class:'col-md-6 col-md-offset-3 btn btn-primary btn-lg'

  section.row.mb40
    .col-md-12
      h2 
        span.glyphicon.glyphicon-thumbs-up
        | &nbsp;あなたはどんな女性が好き？
      h3.graph-title.mt20 あなたはブラジル人が好き
      .bar-graph style="width:32%;"
      .bar-graph-text ブラジル人　32%
      .bar-graph style="width:16%;"
      .bar-graph-text イタリア人　16%
      .bar-graph style="width:12%;"
      .bar-graph-text ドイツ人　12%
      .bar-graph style="width:10%;"
      .bar-graph-text 日本人　10%
      .bar-graph style="width:7%;"
      .bar-graph-text 韓国人　7%
      .bar-graph.bar-graph-other style="width:22%;"
      .bar-graph-text その他　22%
      h3.graph-title あなたはWebデザイナーが好き
      .bar-graph style="width:72%;"
      .bar-graph-text Webデザイナー　72%
      .bar-graph style="width:8%;"
      .bar-graph-text 営業職　8%
      .bar-graph style="width:5%;"
      .bar-graph-text エンジニア　5%
      .bar-graph style="width:3%;"
      .bar-graph-text 経営者　3%
      .bar-graph style="width:2%;"
      .bar-graph-text 管理職　2%
      .bar-graph.bar-graph-other style="width:10%;"
      .bar-graph-text その他　10%
      h3.graph-title あなたは30代が好き
      .bar-graph style="width:54%;"
      .bar-graph-text 30代　54%
      .bar-graph style="width:16%;"
      .bar-graph-text 40代　16%
      .bar-graph style="width:10%;"
      .bar-graph-text 50代　10%
      .bar-graph style="width:7%;"
      .bar-graph-text 20代　7%
      .bar-graph style="width:3%;"
      .bar-graph-text 60代　3%
      .bar-graph.bar-graph-other style="width:10%;"
      .bar-graph-text その他　10%

  section.row
    .col-md-12
      = link_to 'もっと女性を見る', choice_path, class:'col-md-6 col-md-offset-3 btn btn-primary btn-lg'

app/views/statistics/woman.html.slim
article.row.col-md-offset-1.col-md-10.mt20
  section.row
    .col-md-6
      h1.your-rank-title 
        span.glyphicon.glyphicon-user
        | &nbsp;あなたの総合ランク
      p.your-rank
        strong #{@login_user.rank}
        span.your-rank-unit &nbsp;位
    .col-md-6
      table.table.mt100
        tr
          th 表示された回数
          td #{@looked_user_id.size}回
        tr
          th 選ばれた回数
          td #{@selected_user_id.size}回
        tr
          th 選択率
          td #{100 * @looked_user_id.size/@selected_user_id.size}%

  section.row
    .col-md-12
      .row
        .col-md-12
          h2
            span.glyphicon.glyphicon-heart
            | &nbsp;あなたの選んでくれた男性（#{@selected_user_id.uniq.size}人）
      .row
        -User.where(id: @selected_user_id.uniq).each do |user| 
          .col-md-2
            = image_tag user.photo, class:"user-list-image"
            .text-center.user-caption
              strong.user-caption-name #{user.nick_name}
              br 
              | Japan
              br
              | 目利き度 #{user.user_score ? user.user_score.score : "-"}
              br
              - if user.friend_allow? 
                = link_to 'メッセージを送る', "https://www.facebook.com/profile.php?id=#{user.uid}", class:'btn btn-primary btn-sm'
              - else
                span.btn.btn-primary.btn-sm メッセージ不可

  section.row.mt40
    .col-md-12
      h2 
        span.glyphicon.glyphicon-thumbs-up
        | &nbsp;あなたはどんな男性に人気？
      h3.graph-title.mt20 あなたはブラジル人に人気
      .bar-graph style="width:32%;"
      .bar-graph-text ブラジル人　32%
      .bar-graph style="width:16%;"
      .bar-graph-text イタリア人　16%
      .bar-graph style="width:12%;"
      .bar-graph-text ドイツ人　12%
      .bar-graph style="width:10%;"
      .bar-graph-text 日本人　10%
      .bar-graph style="width:7%;"
      .bar-graph-text 韓国人　7%
      .bar-graph.bar-graph-other style="width:22%;"
      .bar-graph-text その他　22%
      h3.graph-title あなたはWebデザイナーに人気
      .bar-graph style="width:72%;"
      .bar-graph-text Webデザイナー　72%
      .bar-graph style="width:8%;"
      .bar-graph-text 営業職　8%
      .bar-graph style="width:5%;"
      .bar-graph-text エンジニア　5%
      .bar-graph style="width:3%;"
      .bar-graph-text 経営者　3%
      .bar-graph style="width:2%;"
      .bar-graph-text 管理職　2%
      .bar-graph.bar-graph-other style="width:10%;"
      .bar-graph-text その他　10%
      h3.graph-title あなたは30代に人気
      .bar-graph style="width:54%;"
      .bar-graph-text 30代　54%
      .bar-graph style="width:16%;"
      .bar-graph-text 40代　16%
      .bar-graph style="width:10%;"
      .bar-graph-text 50代　10%
      .bar-graph style="width:7%;"
      .bar-graph-text 20代　7%
      .bar-graph style="width:3%;"
      .bar-graph-text 60代　3%
      .bar-graph.bar-graph-other style="width:10%;"
      .bar-graph-text その他　10%